//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackDetail
    {
        public int Id { get; set; }
        public Nullable<int> FeedbackID { get; set; }
        public Nullable<int> CriteriaID { get; set; }
        public int Score { get; set; }
    
        public virtual Criteria Criteria { get; set; }
        public virtual Feedback Feedback { get; set; }
    }
}
