//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningMaterial
    {
        public int MaterialId { get; set; }
        public string MaterialUrl { get; set; }
        public int MaterialTypeId { get; set; }
        public string Description { get; set; }
        public int LessonId { get; set; }
        public bool isActived { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual MaterialType MaterialType { get; set; }
    }
}
