//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public int StudentId { get; set; }
        public int TutorId { get; set; }
        public int LessonId { get; set; }
        public int SlotOrder { get; set; }
        public System.DateTime SlotDate { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public string CanReason { get; set; }
        public decimal Price { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
