//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.StudentFeedbacks = new HashSet<StudentFeedback>();
            this.TutorFeedbacks = new HashSet<TutorFeedback>();
        }
    
        public int ScheduleId { get; set; }
        public int TutorId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderSlot { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public int Status { get; set; }
        public Nullable<int> Type { get; set; }
        public string CanReason { get; set; }
        public decimal Price { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeedback> StudentFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorFeedback> TutorFeedbacks { get; set; }
    }
}
