//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        public int Id { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
