//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachSchedule
    {
        public int TeachScheduleId { get; set; }
        public int TutorId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderSlot { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
