//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorFeedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorFeedback()
        {
            this.TutorFeedbackDetails = new HashSet<TutorFeedbackDetail>();
        }
    
        public int TutorFeedbackId { get; set; }
        public int TutorId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public System.DateTime FeedbackDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TestResult { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorFeedbackDetail> TutorFeedbackDetails { get; set; }
    }
}
