//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorFeedbackDetail
    {
        public int TutorFeedbackId { get; set; }
        public int CriteriaId { get; set; }
        public int CriteriaValue { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual TutorFeedback TutorFeedback { get; set; }
    }
}
